Repository ganafgan/project-PWDK, pull requests merged in 2020-06, with the labels that each got.

#1 coba push
  tokobuku/src/App.js
Labels: enhancement

#2 update backend
  tokobuku-be/.gitignore
  tokobuku-be/controller/authentication.js
  tokobuku-be/controller/users.js
  tokobuku-be/database/mysql.js
  tokobuku-be/helpers/hashing.js
  tokobuku-be/index.js
  tokobuku-be/mysql_TokoBuku.sql
  tokobuku-be/package-lock.json
  tokobuku-be/router/authentication.js
  tokobuku-be/router/users.js
  tokobuku-be/tokoBuku.mwb
  tokobuku-be/tokoBuku.mwb.bak
Labels: enhancement

#4 product & user router
  tokobuku-be/controller/products.js
  tokobuku-be/controller/users.js
  tokobuku-be/index.js
  tokobuku-be/package-lock.json
  tokobuku-be/router/products.js
  tokobuku-be/router/users.js
Labels: enhancement

#5 tambah utils font
  tokobuku/src/utils/font/index.js
  tokobuku/src/utils/index.js
Labels: enhancement

#6 fonts
  tokobuku/src/utils/index.js
Labels: enhancement

#8 update_backEnd
  tokobuku-be/.gitignore
  tokobuku-be/controller/authors.js
  tokobuku-be/controller/cart.js
  tokobuku-be/controller/category.js
  tokobuku-be/controller/products.js
  tokobuku-be/controller/publishers.js
  tokobuku-be/controller/ratingReview.js
  tokobuku-be/controller/transaction.js
  tokobuku-be/controller/uploader.js
  tokobuku-be/controller/wishlist.js
  tokobuku-be/helpers/uploader.js
  tokobuku-be/index.js
  tokobuku-be/router/authors.js
  tokobuku-be/router/cart.js
  tokobuku-be/router/category.js
  tokobuku-be/router/publishers.js
  tokobuku-be/router/ratingReview.js
  tokobuku-be/router/transaction.js
  tokobuku-be/router/uploader.js
  tokobuku-be/router/wishlist.js
Labels: enhancement

#9 buat tab navigator
  tokobuku/src/pages/Account/index.js
  tokobuku/src/pages/Cart/index.js
  tokobuku/src/pages/Dashboard/index.js
  tokobuku/src/pages/Home/index.js
  tokobuku/src/pages/Login/index.js
  tokobuku/src/pages/index.js
  tokobuku/src/router/index.js
Labels: enhancement

#11 update backend & dokumentasi postman
  tokobuku-be/controller/authentication.js
  tokobuku-be/controller/cart.js
  tokobuku-be/controller/products.js
  tokobuku-be/controller/uploader.js
  tokobuku-be/controller/wishlist.js
  tokobuku-be/index.js
  tokobuku-be/router/cart.js
  tokobuku-be/router/products.js
  tokobuku-be/router/uploader.js
Labels: documentation, enhancement

#14 'ContentCart'
  tokobuku/src/assets/icon/ic-add-photo.png
  tokobuku/src/assets/icon/ic-minus-button.svg
  tokobuku/src/assets/icon/ic-plus-button.svg
  tokobuku/src/assets/icon/index.js
  tokobuku/src/assets/ilustration/index.js
  tokobuku/src/assets/ilustration/troli.png
  tokobuku/src/components/atoms/NullCart/index.js
  tokobuku/src/components/atoms/index.js
  tokobuku/src/components/moleculs/ContentCart/index.js
  tokobuku/src/components/moleculs/NullCart/index.js
  tokobuku/src/components/moleculs/index.js
  tokobuku/src/pages/Cart/index.js
Labels: enhancement

#13 cart kosong
  tokobuku/src/pages/Cart/index.js
  tokobuku/src/pages/UploadPhoto/index.js
  tokobuku/src/router/index.js
Labels: enhancement

#16 nambah cartpart2
  tokobuku/src/components/moleculs/ContentCarts/index.js
Labels: enhancement

#18 Branch cart
  tokobuku/src/components/moleculs/ContentCarts/index.js
  tokobuku/src/supports/constants/urlApi.js
Labels: enhancement

#19 product list, product detail, wishlist
  tokobuku-be/controller/products.js
  tokobuku-be/controller/wishlist.js
  tokobuku-be/router/products.js
  tokobuku/src/components/moleculs/BookCategory/index.js
  tokobuku/src/components/moleculs/ContentCarts/index.js
  tokobuku/src/components/moleculs/ContentProductDetail/index.js
  tokobuku/src/components/moleculs/HeaderMain/index.js
  tokobuku/src/components/moleculs/ListBook/index.js
  tokobuku/src/components/moleculs/index.js
  tokobuku/src/pages/Home/index.js
  tokobuku/src/pages/ProductDetail/index.js
  tokobuku/src/pages/ProductList/index.js
  tokobuku/src/pages/Wishlist/index.js
  tokobuku/src/pages/index.js
  tokobuku/src/router/index.js
  tokobuku/src/supports/constants/urlApi.js
Labels: enhancement

#20 Icon wishlist
  tokobuku/package-lock.json
  tokobuku/package.json
  tokobuku/src/assets/icon/ic-cart.svg
  tokobuku/src/assets/icon/ic-favorite.svg
  tokobuku/src/assets/icon/index.js
  tokobuku/src/components/moleculs/HeaderSearch/index.js
  tokobuku/src/pages/Home/index.js
  tokobuku/src/pages/ProductDetail/index.js
  tokobuku/src/supports/constants/urlApi.js
Labels: enhancement

#21 Replace product
  tokobuku/src/components/moleculs/HeaderSearch/index.js
  tokobuku/src/pages/Home/index.js
  tokobuku/src/pages/ProductDetail/index.js
  tokobuku/src/pages/Wishlist/index.js
  tokobuku/src/supports/constants/urlApi.js
Labels: enhancement

#23 'nambahtokoadmin'
  tokobuku-admin/.gitignore
  tokobuku-admin/.vscode/launch.json
  tokobuku-admin/README.md
  tokobuku-admin/package-lock.json
  tokobuku-admin/package.json
  tokobuku-admin/public/favicon.ico
  tokobuku-admin/public/index.html
  tokobuku-admin/public/logo192.png
  tokobuku-admin/public/logo512.png
  tokobuku-admin/public/manifest.json
  tokobuku-admin/public/robots.txt
  tokobuku-admin/src/App.js
  tokobuku-admin/src/assets/Logo/BookStoreLogo.png
  tokobuku-admin/src/assets/Logo/logo.png
  tokobuku-admin/src/elements/Navbar.jsx
  tokobuku-admin/src/images/checklist.png
  tokobuku-admin/src/images/close.png
  tokobuku-admin/src/images/success.jpg
  tokobuku-admin/src/index.js
  tokobuku-admin/src/pages/Home.jsx
  tokobuku-admin/src/pages/Login.jsx
  tokobuku-admin/src/pages/ProductList.jsx
  tokobuku-admin/src/pages/Register.jsx
  tokobuku-admin/src/pages/VerificationSuccess.jsx
Labels: enhancement

#24 update + revisi
  tokobuku-be/controller/cart.js
  tokobuku/src/components/moleculs/ContentCarts/index.js
  tokobuku/src/components/moleculs/NullCarts/index.js
  tokobuku/src/components/moleculs/Penerbit/index.js
  tokobuku/src/pages/Cart/index.js
  tokobuku/src/pages/Home/index.js
  tokobuku/src/pages/ProductDetail/index.js
  tokobuku/src/pages/Register/index.js
  tokobuku/src/pages/Wishlist/index.js
  tokobuku/src/supports/constants/urlApi.js
Labels: enhancement

#25 Loading page
  tokobuku/src/components/moleculs/HeaderSearch/index.js
  tokobuku/src/components/moleculs/Loading/index.js
  tokobuku/src/components/moleculs/index.js
  tokobuku/src/pages/Home/index.js
  tokobuku/src/supports/constants/urlApi.js
  tokobuku/src/utils/colors/index.js
Labels: enhancement

#26 user login system
  tokobuku-be/controller/authentication.js
  tokobuku-be/router/authentication.js
  tokobuku/package-lock.json
  tokobuku/package.json
  tokobuku/src/components/atoms/Link/index.js
  tokobuku/src/pages/Account/index.js
  tokobuku/src/pages/Home/index.js
  tokobuku/src/pages/Login/index.js
  tokobuku/src/pages/Otp/index.js
  tokobuku/src/pages/Register/index.js
  tokobuku/src/pages/Splash/index.js
  tokobuku/src/pages/UploadPhoto/index.js
  tokobuku/src/pages/index.js
  tokobuku/src/redux/reducers/index.js
  tokobuku/src/redux/reducers/userReducer.js
  tokobuku/src/router/index.js
  tokobuku/src/supports/constants/urlApi.js
Labels: enhancement

#27 baruLanding
  tokobuku/src/supports/constants/urlApi.js
Labels: enhancement

#29 update
  tokobuku-be/controller/authentication.js
  tokobuku-be/controller/statusTrans.js
  tokobuku-be/controller/transaction.js
  tokobuku-be/controller/uploader.js
  tokobuku-be/controller/users.js
  tokobuku-be/index.js
  tokobuku-be/public/payment/PAY1592969207520.jpg
  tokobuku-be/public/payment/PAY1592970061122.jpg
  tokobuku-be/router/authentication.js
  tokobuku-be/router/statusTrans.js
  tokobuku/android/app/src/main/AndroidManifest.xml
  tokobuku/android/app/src/main/java/com/tokobuku/MainApplication.java
  tokobuku/package-lock.json
  tokobuku/package.json
  tokobuku/src/components/atoms/Input/index.js
  tokobuku/src/components/moleculs/ContentCarts/index.js
  tokobuku/src/components/moleculs/ListTransaction/index.js
  tokobuku/src/components/moleculs/ListTransactionDetail/index.js
  tokobuku/src/components/moleculs/Profile/index.js
  tokobuku/src/components/moleculs/StatusTransaction/index.js
  tokobuku/src/components/moleculs/index.js
  tokobuku/src/pages/Account/index.js
  tokobuku/src/pages/EditProfile/index.js
  tokobuku/src/pages/ForgotPassword/index.js
  tokobuku/src/pages/Home/index.js
  tokobuku/src/pages/Login/index.js
  tokobuku/src/pages/ProductDetail/index.js
  tokobuku/src/pages/ProductList/index.js
  tokobuku/src/pages/Register/index.js
  tokobuku/src/pages/ResetPassword/index.js
  tokobuku/src/pages/Transaction/index.js
  tokobuku/src/pages/TransactionDetail/index.js
  tokobuku/src/pages/UploadPhoto/index.js
  tokobuku/src/pages/Wishlist/index.js
  tokobuku/src/pages/index.js
  tokobuku/src/redux/reducers/userReducer.js
  tokobuku/src/router/index.js
Labels: enhancement

#30 Admin
  tokobuku-admin/src/App.js
  tokobuku-admin/src/pages/AllProduct.jsx
  tokobuku-admin/src/pages/Dashboard.jsx
  tokobuku-admin/src/pages/InputProduct.jsx
  tokobuku-admin/src/pages/Transaction.jsx
  tokobuku-admin/src/pages/TransactionDetail.jsx
  tokobuku-be/public/payment/PAY1592988119606.jpg
  tokobuku/src/router/index.js
  tokobuku/src/supports/constants/urlApi.js
Labels: enhancement

#31 Landing page
  tokobuku/src/supports/constants/urlApi.js
Labels: enhancement

#36 baruCommit
  tokobuku-UserLandingPage/.gitignore
  tokobuku-UserLandingPage/README.md
  tokobuku-UserLandingPage/package-lock.json
  tokobuku-UserLandingPage/package.json
  tokobuku-UserLandingPage/public/favicon.ico
  tokobuku-UserLandingPage/public/index.html
  tokobuku-UserLandingPage/public/logo192.png
  tokobuku-UserLandingPage/public/logo512.png
  tokobuku-UserLandingPage/public/manifest.json
  tokobuku-UserLandingPage/public/robots.txt
  tokobuku-UserLandingPage/src/App.css
  tokobuku-UserLandingPage/src/App.js
  tokobuku-UserLandingPage/src/App.test.js
  tokobuku-UserLandingPage/src/Group 3.svg
  tokobuku-UserLandingPage/src/components/Contact.js
  tokobuku-UserLandingPage/src/components/Main.js
  tokobuku-UserLandingPage/src/components/Thanks.js
  tokobuku-UserLandingPage/src/hero.svg
  tokobuku-UserLandingPage/src/img1.jpg
  tokobuku-UserLandingPage/src/img2.jpg
  tokobuku-UserLandingPage/src/img3.jpg
  tokobuku-UserLandingPage/src/index.css
  tokobuku-UserLandingPage/src/index.js
  tokobuku-UserLandingPage/src/logo.svg
  tokobuku-UserLandingPage/src/routes.js
  tokobuku-UserLandingPage/src/serviceWorker.js
  tokobuku-UserLandingPage/src/setupTests.js
Labels: enhancement

#39 hapusLP
  tokobuku-LP/tokobuku-UserLandingPage.txt
Labels: duplicate
